"""Estructura nueva

Revision ID: 0e521220af5b
Revises: 
Create Date: 2025-11-19 15:47:11.897813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e521220af5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('min_shift_hours', sa.Float(), nullable=False),
    sa.Column('max_shift_hours', sa.Float(), nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('pvd_minutes_per_hour', sa.Integer(), nullable=True),
    sa.Column('number_of_pvds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduling_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('min_daily_hours', sa.Float(), nullable=False),
    sa.Column('max_daily_hours', sa.Float(), nullable=False),
    sa.Column('max_consecutive_work_days', sa.Integer(), nullable=True),
    sa.Column('min_full_weekends_off_per_month', sa.Integer(), nullable=True),
    sa.Column('relevant_skills', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    with op.batch_alter_table('scheduling_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_rules_country_code'), ['country_code'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('bo_sla_hours', sa.Integer(), nullable=False),
    sa.Column('lunes_apertura', sa.String(length=5), nullable=True),
    sa.Column('lunes_cierre', sa.String(length=5), nullable=True),
    sa.Column('martes_apertura', sa.String(length=5), nullable=True),
    sa.Column('martes_cierre', sa.String(length=5), nullable=True),
    sa.Column('miercoles_apertura', sa.String(length=5), nullable=True),
    sa.Column('miercoles_cierre', sa.String(length=5), nullable=True),
    sa.Column('jueves_apertura', sa.String(length=5), nullable=True),
    sa.Column('jueves_cierre', sa.String(length=5), nullable=True),
    sa.Column('viernes_apertura', sa.String(length=5), nullable=True),
    sa.Column('viernes_cierre', sa.String(length=5), nullable=True),
    sa.Column('sabado_apertura', sa.String(length=5), nullable=True),
    sa.Column('sabado_cierre', sa.String(length=5), nullable=True),
    sa.Column('domingo_apertura', sa.String(length=5), nullable=True),
    sa.Column('domingo_cierre', sa.String(length=5), nullable=True),
    sa.Column('weekend_policy', sa.String(length=50), nullable=False),
    sa.Column('min_full_weekends_off_per_month', sa.Integer(), nullable=False),
    sa.Column('required_skills', sa.String(length=255), nullable=True, comment='Habilidades requeridas'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'campaign_id', name='_name_campaign_uc')
    )
    op.create_table('user_campaign_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'campaign_id')
    )
    op.create_table('actuals_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=False),
    sa.Column('actuals_data', sa.Text(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_date', 'segment_id', name='_date_segment_actuals_uc')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.String(length=50), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('scheduling_rule_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=50), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('centro', sa.String(length=100), nullable=True),
    sa.Column('turno_sugerido', sa.String(length=50), nullable=True),
    sa.Column('ventana_lunes', sa.String(length=50), nullable=True),
    sa.Column('ventana_martes', sa.String(length=50), nullable=True),
    sa.Column('ventana_miercoles', sa.String(length=50), nullable=True),
    sa.Column('ventana_jueves', sa.String(length=50), nullable=True),
    sa.Column('ventana_viernes', sa.String(length=50), nullable=True),
    sa.Column('ventana_sabado', sa.String(length=50), nullable=True),
    sa.Column('ventana_domingo', sa.String(length=50), nullable=True),
    sa.Column('modalidad_finde', sa.String(length=20), nullable=True),
    sa.Column('rotacion_mensual_domingo', sa.String(length=20), nullable=True),
    sa.Column('semanas_libres_finde', sa.String(length=20), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('is_concrecion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scheduling_rule_id'], ['scheduling_rules.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('monthly_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('forecast_pivot_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id')
    )
    op.create_table('staffing_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=False),
    sa.Column('agents_online', sa.Text(), nullable=False),
    sa.Column('agents_total', sa.Text(), nullable=False),
    sa.Column('calls_forecast', sa.Text(), nullable=True),
    sa.Column('aht_forecast', sa.Text(), nullable=True),
    sa.Column('reducers_forecast', sa.Text(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('sla_target_percentage', sa.Float(), nullable=True),
    sa.Column('sla_target_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_date', 'segment_id', name='_date_segment_uc')
    )
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('absence_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('is_manual_edit', sa.Boolean(), nullable=True),
    sa.Column('descanso1_he', sa.String(length=5), nullable=True),
    sa.Column('descanso1_hs', sa.String(length=5), nullable=True),
    sa.Column('descanso2_he', sa.String(length=5), nullable=True),
    sa.Column('descanso2_hs', sa.String(length=5), nullable=True),
    sa.Column('pvd1', sa.String(length=5), nullable=True),
    sa.Column('pvd2', sa.String(length=5), nullable=True),
    sa.Column('pvd3', sa.String(length=5), nullable=True),
    sa.Column('pvd4', sa.String(length=5), nullable=True),
    sa.Column('pvd5', sa.String(length=5), nullable=True),
    sa.Column('pvd6', sa.String(length=5), nullable=True),
    sa.Column('pvd7', sa.String(length=5), nullable=True),
    sa.Column('pvd8', sa.String(length=5), nullable=True),
    sa.Column('pvd9', sa.String(length=5), nullable=True),
    sa.Column('pvd10', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'schedule_date', name='_agent_date_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('absences')
    op.drop_table('staffing_results')
    op.drop_table('monthly_forecasts')
    op.drop_table('agents')
    op.drop_table('actuals_data')
    op.drop_table('user_campaign_permission')
    op.drop_table('segments')
    op.drop_table('user')
    with op.batch_alter_table('scheduling_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_rules_country_code'))

    op.drop_table('scheduling_rules')
    op.drop_table('campaign')
    op.drop_table('break_rules')
    # ### end Alembic commands ###
