"""fix unique constraint schedules

Revision ID: d69228362406
Revises: 34edd0916984
Create Date: 2025-11-28 15:39:42.770566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69228362406'
down_revision = '34edd0916984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('_agent_date_scen_uc'))
        batch_op.drop_constraint(batch_op.f('_agent_date_uc'), type_='unique')
        batch_op.create_unique_constraint('_agent_date_scenario_uc', ['agent_id', 'schedule_date', 'scenario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint('_agent_date_scenario_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_agent_date_uc'), ['agent_id', 'schedule_date'])
        batch_op.create_index(batch_op.f('_agent_date_scen_uc'), ['agent_id', 'schedule_date', 'scenario_id'], unique=1)

    # ### end Alembic commands ###
