version: '3.8'

services:
  backend:
    build:
      context: ./sipo
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - ./sipo:/app
      - ./sipo/instance:/app/instance
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/sipo_dev.db
    command: python app.py